name: Deploy to IIS Server

on:
  push:
    branches:
      - main  # Replace 'main' with your branch name if different

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22  # Replace with your Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project
      - name: Build the project
        run: npm run build

      # Step 5: Deploy to IIS Server
      - name: Deploy to IIS Server
        run: |
          Write-Output "Starting deployment process..."
          powershell -File "$env:GITHUB_WORKSPACE\deploy.ps1"
        env:
          BUILD_OUTPUT_PATH: ${{ github.workspace }}\dist
          IIS_DEPLOY_PATH: C:\IIS_Server\dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
